-- JLPT N1 seed data. Loaded once, inside a transaction, when grammar_points is empty.
-- Explicit ids 1..N; sequences start at 10001 so tool-inserted rows never collide.

INSERT INTO grammar_points (id, pattern, reading, meaning, formation, nuance, register) VALUES
(1, '〜んがため(に)', 'んがために', 'in order to; for the sake of (strong purpose)', 'V-ない stem + んがため(に); する → せんがため', 'Literary, expresses a deliberate and strong purpose. The action after ために is done specifically to achieve the goal.', 'literary'),
(2, '〜んばかり(に/だ)', 'んばかりに', 'as if about to; on the verge of', 'V-ない stem + んばかりに; する → せんばかりに', 'Describes a state so extreme it looks as if the action is about to happen. Dramatic, mostly written description.', 'written'),
(3, '〜とばかりに', 'とばかりに', 'as if to say; as though declaring', 'quoted phrase / N + とばかりに', 'The subject acts as if saying the quoted words, without actually saying them. Describes someone else, not the speaker.', 'written'),
(4, '〜ともなると / 〜ともなれば', 'ともなると', 'when it comes to; once it becomes', 'N / V-る + ともなると', 'A special or high-level situation naturally brings different circumstances. Implies things change at that level.', 'neutral'),
(5, '〜をよそに', 'をよそに', 'ignoring; in defiance of; unconcerned by', 'N + をよそに', 'The subject acts without regard for opposition, worry, or expectations around them. Often mildly critical.', 'written'),
(6, '〜を皮切りに(して)', 'をかわきりに', 'starting with; as the first of a series', 'N + を皮切りに(して)', 'An event is the starting point of a series of similar events that follow one after another. Common in news.', 'written'),
(7, '〜たら最後 / 〜たが最後', 'たらさいご', 'once (you do)... it is all over', 'V-たら + 最後 / V-た + が最後', 'Once the action happens, an unavoidable bad situation continues to the end. Strong warning tone.', 'neutral'),
(8, '〜ずくめ', 'ずくめ', 'entirely; nothing but', 'N + ずくめ', 'Everything about it is that thing: 黒ずくめ, いいことずくめ, ごちそうずくめ. Limited set of nouns.', 'neutral'),
(9, '〜まみれ', 'まみれ', 'covered in; smeared with', 'N + まみれ', 'Covered with something dirty or unpleasant that sticks to a surface: 泥, 血, 汗, ほこり, 借金.', 'neutral'),
(10, '〜っぱなし', 'っぱなし', 'left as is; kept doing', 'V-ます stem + っぱなし', 'Something is left in a state it should not be, or a state continues the whole time. Often carries a reproachful tone.', 'spoken'),
(11, '〜かたがた', 'かたがた', 'while also; partly to', 'N + かたがた', 'One action serves two purposes, both intended. Very formal; common in business and greetings: お礼かたがた.', 'formal'),
(12, '〜がてら', 'がてら', 'while; on the occasion of', 'V-ます stem / N + がてら', 'Doing one action, one also does another on the way. Lighter and more casual than かたがた.', 'neutral'),
(13, '〜かたわら', 'かたわら', 'while also (doing a side activity)', 'N の / V-る + かたわら', 'Alongside a main occupation, one also does another long-term activity. Written; for habitual situations, not single events.', 'written'),
(14, '〜そばから', 'そばから', 'as soon as (repeatedly undone)', 'V-る / V-た + そばから', 'Every time the action is done, the result is immediately undone. Expresses exasperation at repetition.', 'neutral'),
(15, '〜なり', 'なり', 'as soon as; the moment', 'V-る + なり', 'The second action happens immediately after the first, often unexpected. Subject is a third person; past events.', 'written'),
(16, '〜や否や / 〜や', 'やいなや', 'no sooner than; the instant', 'V-る + や否や', 'The second event happens almost simultaneously with the first. Literary narration of past events.', 'literary'),
(17, '〜が早いか', 'がはやいか', 'the moment; as soon as', 'V-る + が早いか', 'Emphasizes that the second action followed with almost no interval. Written narration; the second action is intentional.', 'written'),
(18, '〜ところを', 'ところを', 'despite the situation; when (interrupting)', 'N の / Adj / V + ところを', 'Politely acknowledges interrupting or imposing on someone: お忙しいところを. Also: caught in the act of doing.', 'formal'),
(19, '〜ものを', 'ものを', 'if only; and yet (regret, reproach)', 'plain form + ものを', 'Expresses regret or blame that something was not done although it easily could have been.', 'neutral'),
(20, '〜まじき', 'まじき', 'unbefitting; that must not be', 'V-る + まじき + N', 'Set phrase modifying a noun: 許すまじき行為, あるまじき発言. Condemns behavior that violates a role or ethics.', 'literary'),
(21, '〜べからず / 〜べからざる', 'べからず', 'must not; forbidden', 'V-る + べからず (sentence-final) / べからざる + N', 'Archaic prohibition seen on signs and in maxims: 立ち入るべからず. べからざる modifies nouns: 欠くべからざる存在.', 'archaic'),
(22, '〜ならでは', 'ならでは', 'unique to; only possible for', 'N + ならでは(の)', 'Praises a quality that only that person, place, or thing could produce: 京都ならではの風情.', 'neutral'),
(23, '〜をもって', 'をもって', 'by means of; as of (time)', 'N + をもって', 'Formal instrumental (実力をもって) or a formal boundary in time: 本日をもって閉店いたします.', 'formal'),
(24, '〜たりとも', 'たりとも', 'not even (one)', '1 + counter + たりとも + negative', 'Absolutely no exceptions, not even the smallest unit: 一秒たりとも無駄にできない.', 'written'),
(25, '〜だに', 'だに', 'even (just)', 'V-る / N + だに', 'Even just imagining or hearing is enough: 想像するだに恐ろしい. With negative: not even a little (微動だにしない).', 'literary'),
(26, '〜すら', 'すら', 'even', 'N (+ で/に) + すら', 'Presents an extreme example: even X, so everything else goes without saying. More literary than さえ.', 'written'),
(27, '〜からある / 〜からする / 〜からの', 'からある', 'as much as; no less than', 'number + からある (size, weight) / からする (price) / からの (amount, people)', 'Emphasizes that a quantity is impressively large: 100キロからある荷物, 100万円からする時計.', 'written'),
(28, '〜きらいがある', 'きらいがある', 'has a (bad) tendency to', 'V-る / N の + きらいがある', 'Points out an undesirable tendency, usually of people or organizations. Detached, critical, written tone.', 'written'),
(29, '〜(が)ゆえ(に)', 'ゆえに', 'because of; owing to', 'N / Adj / V (+ が) + ゆえ(に)', 'Literary expression of cause. ゆえの modifies nouns: 若さゆえの過ち.', 'literary'),
(30, '〜こととて', 'こととて', 'because; given that (apologetic)', 'N の / V + こととて', 'States a reason while apologizing or asking for understanding: 慣れぬこととて. Old-fashioned and formal.', 'formal'),
(31, '〜とはいえ', 'とはいえ', 'that said; though admittedly', 'N / plain form + とはいえ', 'Admits a fact but states the reality differs from what it implies. Written contrast.', 'written'),
(32, '〜といえども', 'といえども', 'even; even though', 'N / plain form + といえども', 'Even for an extreme case, the statement still holds: 子供といえども容赦しない. Literary.', 'literary'),
(33, '〜ながら(も)', 'ながらも', 'although; despite', 'V-ます stem / Adj / N + ながら(も)', 'Concessive: 狭いながらも楽しい我が家. The two clauses share a subject.', 'neutral'),
(34, '〜ながらに(して)', 'ながらに', 'while remaining; from (birth)', 'N / V-ます stem + ながらに(して)', 'A state continues unchanged: 生まれながらにして (from birth), 涙ながらに (in tears), 居ながらにして (without leaving home).', 'literary'),
(35, '〜なくして(は)', 'なくしては', 'without', 'N + なくして(は) + negative', 'Without X, the outcome is impossible: 努力なくして成功はない. Written, somewhat solemn.', 'written'),
(36, '〜なしに(は) / 〜なしでは', 'なしには', 'without', 'N + なしに(は)', 'Without doing X, Y cannot happen: 予告なしに, 涙なしには語れない.', 'written'),
(37, '〜をおいて', 'をおいて', 'other than; apart from', 'N + をおいて + negative', 'No one and nothing but X qualifies: 彼をおいて適任者はいない. High praise.', 'written'),
(38, '〜にひきかえ', 'にひきかえ', 'in stark contrast to', 'N (+ である の) / V の + にひきかえ', 'Contrasts two things that differ greatly, often with an evaluative or envious tone. Subjective comparison.', 'neutral'),
(39, '〜にもまして', 'にもまして', 'even more than', 'N + にもまして', 'X is already considerable, but Y exceeds it: 以前にもまして元気だ. Often with 誰/何/いつ + にもまして.', 'written'),
(40, '〜はおろか', 'はおろか', 'let alone; not to mention', 'N + はおろか', 'Not even the basic case holds, let alone the greater one. Usually negative, often with さえ/も.', 'written'),
(41, '〜もさることながら', 'もさることながら', 'not only... but especially', 'N + もさることながら', 'X is indeed notable, but Y deserves even more attention. Formal, evaluative, usually positive.', 'formal'),
(42, '〜限りだ', 'かぎりだ', 'extremely (emotion)', 'i-Adj / na-Adj な + 限りだ', 'The speaker feels the emotion to the utmost degree: うらやましい限りだ, 心強い限りだ. About one own feelings.', 'written'),
(43, '〜極まる / 〜極まりない', 'きわまる', 'extremely; utterly', 'na-Adj + 極まる / 極まりない', 'The degree is extreme, usually negative evaluation: 失礼極まりない, 危険極まりない. Both forms mean the same.', 'written'),
(44, '〜の至り', 'のいたり', 'the utmost of', 'N + の至り', 'Ceremonial superlative for feelings: 光栄の至り, 恐縮の至り. Very formal speeches and letters.', 'formal'),
(45, '〜の極み', 'のきわみ', 'the height of; the epitome of', 'N + の極み', 'The extreme point of a state: 贅沢の極み, 感激の極み. Formal, slightly literary.', 'formal'),
(46, '〜てやまない', 'てやまない', 'unceasingly; from the heart', 'V-て + やまない', 'A strong feeling (hope, love, respect) that never ceases: 願ってやまない. Formal writing and speeches.', 'formal'),
(47, '〜に堪えない', 'にたえない', 'cannot bear to; overwhelmed with', 'V-る + に堪えない (見る, 聞く) / N + に堪えない (感謝, 遺憾)', 'With 見る/聞く: too awful to bear seeing or hearing. With emotion nouns: feel it so strongly it cannot be suppressed.', 'formal'),
(48, '〜を禁じ得ない', 'をきんじえない', 'cannot suppress (an emotion)', 'N + を禁じ得ない', 'A natural surge of emotion cannot be held back: 怒りを禁じ得ない, 同情を禁じ得ない. Written, formal.', 'written'),
(49, '〜を余儀なくされる', 'をよぎなくされる', 'be forced to', 'N + を余儀なくされる', 'Circumstances leave no choice but the unwelcome action: 撤退を余儀なくされた. News and reports. 余儀なくさせる: to force.', 'written'),
(50, '〜ずにはおかない / 〜ないではおかない', 'ずにはおかない', 'will inevitably; cannot help but', 'V-ない stem + ずにはおかない', 'The thing has a force that inevitably causes the result, regardless of intention: 感動させずにはおかない.', 'written'),
(51, '〜ないではすまない / 〜ずにはすまない', 'ずにはすまない', 'cannot get away without', 'V-ない stem + ずにはすまない', 'Socially or morally, the action cannot be avoided: 謝らずにはすまない.', 'written'),
(52, '〜べく', 'べく', 'in order to', 'V-る + べく; する → すべく', 'Literary purpose connector: 真相を確かめるべく現地へ向かった. The following clause states what one does for it.', 'written'),
(53, '〜べくして', 'べくして', 'inevitably; as was bound to happen', 'V-る + べくして + V-た', 'The result happened because conditions made it inevitable: 起こるべくして起こった事故.', 'written'),
(54, '〜べくもない', 'べくもない', 'cannot possibly', 'V-る + べくもない', 'The situation gives no possibility at all: 知るべくもない, 望むべくもない. Literary resignation.', 'literary'),
(55, '〜に足る', 'にたる', 'worthy of; sufficient to', 'V-る / N + に足る', 'Deserves or suffices for: 信頼に足る人物, 尊敬に足る. Formal evaluation.', 'written'),
(56, '〜にかたくない', 'にかたくない', 'not hard to (imagine)', 'N / V-る + にかたくない', 'Easy to imagine or understand from circumstances: 想像にかたくない, 察するにかたくない. Written; limited verbs.', 'written'),
(57, '〜のではあるまいか', 'のではあるまいか', 'is it not perhaps that', 'plain form + のではあるまいか', 'Cautious conjecture in writing, equivalent to のではないだろうか.', 'written'),
(58, '〜まい', 'まい', 'probably not; will not', 'V-る + まい; する → しまい/すまい', 'Negative conjecture (二度とあるまい) or negative volition (もう行くまい). Written and somewhat old-fashioned.', 'written'),
(59, '〜であれ / 〜であろうと', 'であれ', 'no matter what; even if', 'N + であれ', 'Even in that case, the statement holds: たとえ王であれ法には従う. Formal generalization.', 'written'),
(60, '〜であれ〜であれ', 'であれであれ', 'whether A or B', 'N + であれ + N + であれ', 'In either case, the same holds: 男であれ女であれ.', 'written'),
(61, '〜といい〜といい', 'といいといい', 'both in A and in B', 'N + といい + N + といい', 'Citing two aspects as examples, gives an overall (often admiring or critical) evaluation: 色といい形といい.', 'neutral'),
(62, '〜といわず〜といわず', 'といわずといわず', 'not just A or B but everywhere', 'N + といわず + N + といわず', 'Not only these parts but the whole, without distinction: 手といわず足といわず泥だらけ.', 'written'),
(63, '〜なり〜なり', 'なりなり', 'either A or B (for example)', 'V-る / N + なり + V-る / N + なり', 'Suggests options, any of which is fine: 電話するなりメールするなりしてください. Suggestion or advice.', 'neutral'),
(64, '〜つ〜つ', 'つつ', 'alternating actions', 'V-ます stem + つ + V-ます stem + つ', 'Fixed pairs of alternating actions: 行きつ戻りつ, 浮きつ沈みつ, 抜きつ抜かれつ. Literary.', 'literary'),
(65, '〜(よ)うが / 〜(よ)うと', 'ようが', 'no matter how; even if', 'V-volitional / Adj-かろう + が/と', 'Whatever happens, it makes no difference: 誰が何と言おうが構わない.', 'neutral'),
(66, '〜(よ)うが〜まいが / 〜(よ)うと〜まいと', 'ようがまいが', 'whether or not', 'V-volitional + が + V-る + まいが', 'Either way, the result is unaffected: 雨が降ろうが降るまいが決行する.', 'neutral'),
(67, '〜(よ)うにも〜ない', 'ようにもない', 'want to but cannot', 'V-volitional + にも + V-potential negative', 'One tries or wants to act but circumstances make it impossible: 逃げようにも逃げられない.', 'neutral'),
(68, '〜にあって', 'にあって', 'in; at (a special situation)', 'N + にあって', 'In an exceptional time, place, or position: この非常時にあって. Formal, written.', 'formal'),
(69, '〜に即して', 'にそくして', 'in line with; in accordance with', 'N + に即して', 'Following facts, experience, rules, or the actual situation: 実情に即して判断する.', 'formal'),
(70, '〜に照らして', 'にてらして', 'in light of', 'N + に照らして', 'Judging by comparison with a standard, law, or precedent: 法律に照らして処罰する.', 'formal'),
(71, '〜を限りに', 'をかぎりに', 'as of; ending with', 'N (time) + を限りに', 'A continuing activity ends at that point: 今日を限りに禁煙する. Also 声を限りに: at the top of one voice.', 'written'),
(72, '〜ぐるみ', 'ぐるみ', 'involving the whole', 'N + ぐるみ', 'Everything included, acting as one: 家族ぐるみ, 会社ぐるみ, 地域ぐるみ.', 'neutral'),
(73, '〜ごとき / 〜ごとく', 'ごとき', 'like; as (literary)', 'N の + ごとき + N / ごとく + V; V-る/た + が + ごとき', 'Literary simile (雪のごとく白い). N + ごとき can belittle: 私ごとき (humble), 彼ごとき (contemptuous).', 'literary'),
(74, '〜ときたら', 'ときたら', 'when it comes to (complaint)', 'N + ときたら', 'Brings up something close to the speaker and complains about it: うちの息子ときたら. Conversational.', 'spoken'),
(75, '〜ともなく / 〜ともなしに', 'ともなく', 'without particular intention', 'V-る + ともなく / 疑問詞(+particle) + ともなく', 'Doing something absently (見るともなく見ていた), or an unclear where/when/who: どこからともなく.', 'neutral'),
(76, '〜ないまでも', 'ないまでも', 'even if not to that extent', 'V-ない + までも', 'Even if the higher level is not reached, at least the lower one holds: 毎日とは言わないまでも週に一度は.', 'written'),
(77, '〜ならいざしらず', 'ならいざしらず', 'I do not know about X, but', 'N + ならいざしらず', 'X might be an exception, but for the case at hand the statement definitely applies: 新人ならいざしらず.', 'neutral'),
(78, '〜はさておき', 'はさておき', 'setting aside', 'N + はさておき', 'Puts one topic aside to prioritize another: 冗談はさておき.', 'neutral'),
(79, '〜てからというもの', 'てからというもの', 'ever since', 'V-て + からというもの', 'Since that event, a big change has continued: 子供が生まれてからというもの. Emotive retrospection.', 'written'),
(80, '〜と相まって', 'とあいまって', 'combined with', 'N + と相まって', 'Two factors combine to heighten the effect: 天候と相まって被害が拡大した. Written, formal.', 'written'),
(81, '〜なりに / 〜なりの', 'なりに', 'in one own way', 'N / Adj / V + なりに', 'Within the limits of what one is, making a fitting effort: 子供なりに考えた, 私なりの答え. Humble about oneself.', 'neutral'),
(82, '〜いかんだ / 〜いかんによっては', 'いかんだ', 'depending on', 'N (+ の) + いかんだ / いかんによっては', 'The outcome is determined by X: 結果は努力のいかんだ. Formal, administrative.', 'formal'),
(83, '〜いかんにかかわらず / 〜いかんによらず', 'いかんにかかわらず', 'regardless of', 'N + のいかんにかかわらず / いかんを問わず', 'Whatever X may be, it does not affect the matter: 理由のいかんにかかわらず返品不可. Official notices.', 'formal'),
(84, '〜をものともせず(に)', 'をものともせず', 'in defiance of; unfazed by', 'N + をものともせず(に)', 'Bravely acting without letting the obstacle matter. Admiring tone; not used of oneself.', 'written'),
(85, '〜を顧みず / 〜も顧みず', 'をかえりみず', 'without regard for', 'N + を顧みず', 'Acting while disregarding danger or personal cost: 危険を顧みず人命を救助した.', 'written'),
(86, '〜てはばからない', 'てはばからない', 'unabashedly; without hesitation', 'V-て + はばからない', 'Says or does something bold openly, without fear of criticism: 公言してはばからない.', 'written'),
(87, '〜に至って / 〜に至るまで', 'にいたって', 'only when it reached; up to and including', 'N / V-る + に至って(初めて) / N + に至るまで', 'Only at that extreme stage did something happen (事ここに至って); or coverage extends even to: 靴下に至るまで.', 'written'),
(88, '〜始末だ', 'しまつだ', 'ended up (deplorably)', 'V-る + 始末だ', 'After a series of bad developments, it ended in this sorry state: 挙句の果てに辞めると言い出す始末だ. Critical.', 'neutral'),
(89, '〜ばそれまでだ', 'ばそれまでだ', 'if... then it is all over', 'V-ば + それまでだ', 'If that happens, everything comes to nothing: 死んでしまえばそれまでだ. Resigned tone.', 'neutral'),
(90, '〜までもない', 'までもない', 'no need to even', 'V-る + までもない', 'The matter is so obvious or trivial that the action is unnecessary: 言うまでもない.', 'neutral'),
(91, '〜ばこそ', 'ばこそ', 'precisely because', 'V-ば / Adj-ければ / N であれば + こそ', 'Emphasizes that this, and nothing else, is the reason — usually a positive reason: あなたのためを思えばこそ. Ends with のだ often.', 'written'),
(92, '〜の一途をたどる', 'のいっとをたどる', 'to keep (worsening/improving) steadily', 'N + の一途をたどる', 'A trend continues in one direction only, usually decline: 悪化の一途をたどる. News style.', 'written');

INSERT INTO grammar_examples (id, grammar_id, japanese, reading, english) VALUES
(1, 1, '勝たんがために、彼は厳しい練習に耐えた。', 'かたんがために、かれはきびしいれんしゅうにたえた。', 'He endured harsh training in order to win.'),
(2, 1, '真実を知らんがため、あらゆる資料を調べた。', 'しんじつをしらんがため、あらゆるしりょうをしらべた。', 'I examined every document in order to learn the truth.'),
(3, 2, '彼女は泣かんばかりの顔で謝った。', 'かのじょはなかんばかりのかおであやまった。', 'She apologized looking as if she were about to cry.'),
(4, 2, '店には溢れんばかりの商品が並んでいた。', 'みせにはあふれんばかりのしょうひんがならんでいた。', 'The shop was lined with goods practically overflowing.'),
(5, 3, '彼は早く帰れとばかりに、時計をちらちら見た。', 'かれははやくかえれとばかりに、とけいをちらちらみた。', 'He kept glancing at the clock as if to say: hurry up and leave.'),
(6, 3, '今がチャンスとばかりに、一気に攻め込んだ。', 'いまがちゃんすとばかりに、いっきにせめこんだ。', 'Seizing what seemed the perfect moment, they attacked all at once.'),
(7, 4, '大企業の社長ともなると、自由な時間はほとんどない。', 'だいきぎょうのしゃちょうともなると、じゆうなじかんはほとんどない。', 'Once you become president of a large company, you have almost no free time.'),
(8, 4, '連休ともなれば、この辺りは観光客でいっぱいだ。', 'れんきゅうともなれば、このあたりはかんこうきゃくでいっぱいだ。', 'Come a long holiday, this area is packed with tourists.'),
(9, 5, '親の心配をよそに、彼は一人で世界一周の旅に出た。', 'おやのしんぱいをよそに、かれはひとりでせかいいっしゅうのたびにでた。', 'Ignoring his parents worries, he set off alone on a trip around the world.'),
(10, 5, '住民の反対をよそに、工事は着々と進められた。', 'じゅうみんのはんたいをよそに、こうじはちゃくちゃくとすすめられた。', 'In defiance of residents opposition, the construction proceeded steadily.'),
(11, 6, '東京公演を皮切りに、全国ツアーが始まった。', 'とうきょうこうえんをかわきりに、ぜんこくつあーがはじまった。', 'Starting with the Tokyo performance, the nationwide tour began.'),
(12, 6, 'その発言を皮切りに、批判が相次いだ。', 'そのはつげんをかわきりに、ひはんがあいついだ。', 'That remark set off a series of criticisms.'),
(13, 7, '彼は飲み出したら最後、朝まで止まらない。', 'かれはのみだしたらさいご、あさまでとまらない。', 'Once he starts drinking, there is no stopping him until morning.'),
(14, 7, 'あの男に金を貸したが最後、二度と返ってこない。', 'あのおとこにかねをかしたがさいご、にどとかえってこない。', 'Lend that man money and you will never see it again.'),
(15, 8, '彼女は今日も黒ずくめの服装だ。', 'かのじょはきょうもくろずくめのふくそうだ。', 'She is dressed all in black again today.'),
(16, 8, '今年はいいことずくめの一年だった。', 'ことしはいいことずくめのいちねんだった。', 'This year was full of nothing but good things.'),
(17, 9, '子供たちは泥まみれになって遊んでいた。', 'こどもたちはどろまみれになってあそんでいた。', 'The children were playing, covered in mud.'),
(18, 9, '彼は借金まみれの生活から抜け出した。', 'かれはしゃっきんまみれのせいかつからぬけだした。', 'He escaped from a life buried in debt.'),
(19, 10, '窓を開けっぱなしにして出かけてしまった。', 'まどをあけっぱなしにしてでかけてしまった。', 'I went out leaving the window wide open.'),
(20, 10, '今日は一日中立ちっぱなしで疲れた。', 'きょうはいちにちじゅうたちっぱなしでつかれた。', 'I was on my feet all day today and I am exhausted.'),
(21, 11, 'お礼かたがた、近況をご報告いたします。', 'おれいかたがた、きんきょうをごほうこくいたします。', 'I write to thank you and also to report how I have been.'),
(22, 12, '散歩がてら、郵便局に寄ってきた。', 'さんぽがてら、ゆうびんきょくによってきた。', 'While out for a walk, I stopped by the post office.'),
(23, 13, '彼は会社勤めのかたわら、小説を書いている。', 'かれはかいしゃづとめのかたわら、しょうせつをかいている。', 'While working at a company, he also writes novels.'),
(24, 14, '習ったそばから忘れてしまう。', 'ならったそばからわすれてしまう。', 'I forget things the moment I learn them.'),
(25, 15, '彼は部屋に入るなり、倒れ込んだ。', 'かれはへやにはいるなり、たおれこんだ。', 'The moment he entered the room, he collapsed.'),
(26, 16, 'ベルが鳴るや否や、生徒たちは教室を飛び出した。', 'べるがなるやいなや、せいとたちはきょうしつをとびだした。', 'No sooner had the bell rung than the students dashed out of the classroom.'),
(27, 17, '彼は席に着くが早いか、弁当を広げた。', 'かれはせきにつくがはやいか、べんとうをひろげた。', 'The moment he sat down, he opened his boxed lunch.'),
(28, 18, 'お忙しいところをお越しいただき、ありがとうございます。', 'おいそがしいところをおこしいただき、ありがとうございます。', 'Thank you for coming despite being so busy.'),
(29, 19, '早く医者に行けばよかったものを、我慢するから悪化したのだ。', 'はやくいしゃにいけばよかったものを、がまんするからあっかしたのだ。', 'If only you had gone to the doctor sooner — because you toughed it out, it got worse.'),
(30, 20, 'それは教師にあるまじき行為だ。', 'それはきょうしにあるまじきこういだ。', 'That is conduct unbefitting a teacher.'),
(31, 21, '芝生に入るべからず。', 'しばふにはいるべからず。', 'Keep off the grass.'),
(32, 21, '彼はチームに欠くべからざる存在だ。', 'かれはちーむにかくべからざるそんざいだ。', 'He is an indispensable member of the team.'),
(33, 22, 'この味は老舗ならではのものだ。', 'このあじはしにせならではのものだ。', 'This flavor is something only a long-established shop could produce.'),
(34, 23, '本日をもって当店は閉店いたします。', 'ほんじつをもってとうてんはへいてんいたします。', 'As of today, our shop is closing.'),
(35, 24, '一秒たりとも無駄にはできない。', 'いちびょうたりともむだにはできない。', 'Not even a single second can be wasted.'),
(36, 25, 'あの事故のことは思い出すだに恐ろしい。', 'あのじこのことはおもいだすだにおそろしい。', 'Even just remembering that accident is terrifying.'),
(37, 26, '彼は自分の名前すら書けなかった。', 'かれはじぶんのなまえすらかけなかった。', 'He could not even write his own name.'),
(38, 27, '20キロからある荷物を一人で運んだ。', 'にじゅっきろからあるにもつをひとりではこんだ。', 'I carried a load weighing no less than twenty kilos by myself.'),
(39, 28, '彼は物事を悲観的に考えるきらいがある。', 'かれはものごとをひかんてきにかんがえるきらいがある。', 'He has a tendency to view things pessimistically.'),
(40, 29, '若さゆえの過ちだったと反省している。', 'わかさゆえのあやまちだったとはんせいしている。', 'I now see it was a mistake born of youth.'),
(41, 30, '慣れぬこととて、ご迷惑をおかけしました。', 'なれぬこととて、ごめいわくをおかけしました。', 'Being new to this, I am afraid I caused you trouble.'),
(42, 31, '春とはいえ、朝晩はまだ冷える。', 'はるとはいえ、あさばんはまだひえる。', 'Spring though it is, mornings and evenings are still chilly.'),
(43, 32, '専門家といえども、間違えることはある。', 'せんもんかといえども、まちがえることはある。', 'Even experts sometimes make mistakes.'),
(44, 33, '残念ながらも、今回は諦めることにした。', 'ざんねんながらも、こんかいはあきらめることにした。', 'Though it was disappointing, I decided to give up this time.'),
(45, 34, '彼女は涙ながらに事情を語った。', 'かのじょはなみだながらにじじょうをかたった。', 'In tears, she explained the situation.'),
(46, 34, 'インターネットのおかげで、居ながらにして世界中の情報が手に入る。', 'いんたーねっとのおかげで、いながらにしてせかいじゅうのじょうほうがてにはいる。', 'Thanks to the internet, you can get information from all over the world without leaving home.'),
(47, 35, '皆様のご協力なくしては、成功はあり得ませんでした。', 'みなさまのごきょうりょくなくしては、せいこうはありえませんでした。', 'Without everyone cooperation, success would have been impossible.'),
(48, 36, '彼は断りなしに会社を休んだ。', 'かれはことわりなしにかいしゃをやすんだ。', 'He took the day off without notice.'),
(49, 37, 'この役を演じられるのは彼女をおいて他にいない。', 'このやくをえんじられるのはかのじょをおいてほかにいない。', 'No one but her could play this role.'),
(50, 38, '兄が社交的なのにひきかえ、弟は内気だ。', 'あにがしゃこうてきなのにひきかえ、おとうとはうちきだ。', 'In stark contrast to his sociable older brother, the younger one is shy.'),
(51, 39, '今年は例年にもまして暑い。', 'ことしはれいねんにもましてあつい。', 'This year is even hotter than usual.'),
(52, 40, '彼は漢字はおろか、ひらがなも書けない。', 'かれはかんじはおろか、ひらがなもかけない。', 'He cannot write hiragana, let alone kanji.'),
(53, 41, 'この旅館は料理もさることながら、眺めが素晴らしい。', 'このりょかんはりょうりもさることながら、ながめがすばらしい。', 'At this inn the food is excellent, but the view is even more remarkable.'),
(54, 42, '長年の夢が叶って、うれしい限りだ。', 'ながねんのゆめがかなって、うれしいかぎりだ。', 'My long-held dream has come true — I could not be happier.'),
(55, 43, '客の前であくびをするとは、失礼極まりない。', 'きゃくのまえであくびをするとは、しつれいきわまりない。', 'Yawning in front of a customer is the height of rudeness.'),
(56, 44, 'このような賞をいただき、光栄の至りです。', 'このようなしょうをいただき、こうえいのいたりです。', 'Receiving such an award is the greatest of honors.'),
(57, 45, '三日間働き続けて、疲労の極みに達した。', 'みっかかんはたらきつづけて、ひろうのきわみにたっした。', 'After working three days straight, I reached the peak of exhaustion.'),
(58, 46, '皆様のご健康を願ってやみません。', 'みなさまのごけんこうをねがってやみません。', 'I wish you all good health from the bottom of my heart.'),
(59, 47, '事故現場は見るに堪えない有様だった。', 'じこげんばはみるにたえないありさまだった。', 'The accident scene was too terrible to look at.'),
(60, 47, '皆様のご支援に感謝に堪えません。', 'みなさまのごしえんにかんしゃにたえません。', 'I am filled with gratitude for your support.'),
(61, 48, 'その判決には怒りを禁じ得なかった。', 'そのはんけつにはいかりをきんじえなかった。', 'I could not suppress my anger at the verdict.'),
(62, 49, '台風のため、大会は中止を余儀なくされた。', 'たいふうのため、たいかいはちゅうしをよぎなくされた。', 'Because of the typhoon, the tournament had to be called off.'),
(63, 50, 'この映画は観る者を感動させずにはおかない。', 'このえいがはみるものをかんどうさせずにはおかない。', 'This film never fails to move those who see it.'),
(64, 51, 'これだけ迷惑をかけたのだから、謝らずにはすまない。', 'これだけめいわくをかけたのだから、あやまらずにはすまない。', 'Having caused this much trouble, I cannot get away without apologizing.'),
(65, 52, '真相を確かめるべく、記者は現地へ飛んだ。', 'しんそうをたしかめるべく、きしゃはげんちへとんだ。', 'The reporter flew to the scene to confirm the truth.'),
(66, 53, 'あれは起こるべくして起こった事故だ。', 'あれはおこるべくしておこったじこだ。', 'That was an accident bound to happen.'),
(67, 54, '当時の人々の暮らしぶりは、今となっては知るべくもない。', 'とうじのひとびとのくらしぶりは、いまとなってはしるべくもない。', 'How people lived back then, we now have no way of knowing.'),
(68, 55, '彼は信頼に足る人物だ。', 'かれはしんらいにたるじんぶつだ。', 'He is a person worthy of trust.'),
(69, 56, '彼女の悲しみは察するにかたくない。', 'かのじょのかなしみはさっするにかたくない。', 'Her grief is not hard to imagine.'),
(70, 57, 'この計画には無理があるのではあるまいか。', 'このけいかくにはむりがあるのではあるまいか。', 'Is this plan not perhaps overambitious?'),
(71, 58, 'こんなチャンスは二度とあるまい。', 'こんなちゃんすはにどとあるまい。', 'A chance like this will probably never come again.'),
(72, 59, 'たとえ相手が誰であれ、ルールは守ってもらう。', 'たとえあいてがだれであれ、るーるはまもってもらう。', 'No matter who it is, they will follow the rules.'),
(73, 60, '賛成であれ反対であれ、必ず投票してください。', 'さんせいであれはんたいであれ、かならずとうひょうしてください。', 'Whether you are for or against, please be sure to vote.'),
(74, 61, '色といい柄といい、この着物は彼女によく似合う。', 'いろといいがらといい、このきものはかのじょによくにあう。', 'In both color and pattern, this kimono suits her perfectly.'),
(75, 62, '子供たちは手といわず足といわず、泥だらけだった。', 'こどもたちはてといわずあしといわず、どろだらけだった。', 'The children were covered in mud — hands, feet, everywhere.'),
(76, 63, '分からないことは、先生に聞くなり辞書で調べるなりしなさい。', 'わからないことは、せんせいにきくなりじしょでしらべるなりしなさい。', 'If there is something you do not understand, ask the teacher or look it up in a dictionary.'),
(77, 64, '彼は玄関の前を行きつ戻りつしていた。', 'かれはげんかんのまえをいきつもどりつしていた。', 'He was pacing back and forth in front of the entrance.'),
(78, 65, '人に何と言われようが、私は自分の道を行く。', 'ひとになんといわれようが、わたしはじぶんのみちをいく。', 'Whatever people may say, I will go my own way.'),
(79, 66, '雨が降ろうが降るまいが、試合は行われる。', 'あめがふろうがふるまいが、しあいはおこなわれる。', 'Rain or no rain, the match will be held.'),
(80, 67, '道が渋滞していて、急ごうにも急げなかった。', 'みちがじゅうたいしていて、いそごうにもいそげなかった。', 'The roads were jammed; I wanted to hurry but could not.'),
(81, 68, 'この不況下にあって、あの会社だけは業績を伸ばしている。', 'このふきょうかにあって、あのかいしゃだけはぎょうせきをのばしている。', 'Even in this recession, that company alone keeps growing.'),
(82, 69, '実情に即して、柔軟に対応すべきだ。', 'じつじょうにそくして、じゅうなんにたいおうすべきだ。', 'We should respond flexibly, in line with the actual situation.'),
(83, 70, 'その行為は法に照らして罰せられるべきだ。', 'そのこういはほうにてらしてばっせられるべきだ。', 'That act should be punished in light of the law.'),
(84, 71, '今日を限りに、たばこをやめることにした。', 'きょうをかぎりに、たばこをやめることにした。', 'I decided to quit smoking as of today.'),
(85, 72, 'この祭りは町ぐるみで開催される。', 'このまつりはまちぐるみでかいさいされる。', 'This festival is put on by the whole town together.'),
(86, 73, '彼女は氷のごとき冷たい目で私を見た。', 'かのじょはこおりのごときつめたいめでわたしをみた。', 'She looked at me with eyes as cold as ice.'),
(87, 74, 'うちの息子ときたら、休みの日は寝てばかりいる。', 'うちのむすこときたら、やすみのひはねてばかりいる。', 'That son of mine — on his days off all he does is sleep.'),
(88, 75, 'テレビを見るともなく見ていたら、母校が映った。', 'てれびをみるともなくみていたら、ぼこうがうつった。', 'I was absently watching TV when my old school appeared on screen.'),
(89, 76, '毎日とは言わないまでも、週に一度は掃除をしなさい。', 'まいにちとはいわないまでも、しゅうにいちどはそうじをしなさい。', 'Clean up at least once a week, if not every day.'),
(90, 77, '新入社員ならいざしらず、入社十年のあなたがこんなミスをするとは。', 'しんにゅうしゃいんならいざしらず、にゅうしゃじゅうねんのあなたがこんなみすをするとは。', 'A new employee, maybe — but you, ten years in, making this mistake?'),
(91, 78, '冗談はさておき、本題に入りましょう。', 'じょうだんはさておき、ほんだいにはいりましょう。', 'Joking aside, let us get down to business.'),
(92, 79, '彼女に出会ってからというもの、毎日が楽しくてたまらない。', 'かのじょにであってからというもの、まいにちがたのしくてたまらない。', 'Ever since I met her, every day has been a joy.'),
(93, 80, '好天と相まって、祭りは大勢の人でにぎわった。', 'こうてんとあいまって、まつりはおおぜいのひとでにぎわった。', 'Combined with the fine weather, the festival drew great crowds.'),
(94, 81, '子供は子供なりに悩みを抱えている。', 'こどもはこどもなりになやみをかかえている。', 'Children have worries of their own, in their own way.'),
(95, 82, '合否は面接の結果いかんだ。', 'ごうひはめんせつのけっかいかんだ。', 'Acceptance depends on the outcome of the interview.'),
(96, 83, '理由のいかんにかかわらず、暴力は許されない。', 'りゆうのいかんにかかわらず、ぼうりょくはゆるされない。', 'Whatever the reason, violence is not tolerated.'),
(97, 84, '彼女は足のけがをものともせず、決勝まで勝ち進んだ。', 'かのじょはあしのけがをものともせず、けっしょうまでかちすすんだ。', 'Undaunted by her leg injury, she fought her way to the final.'),
(98, 85, '彼は危険を顧みず、川に飛び込んで子供を助けた。', 'かれはきけんをかえりみず、かわにとびこんでこどもをたすけた。', 'Without regard for the danger, he leapt into the river and saved the child.'),
(99, 86, '彼は自分が天才だと公言してはばからない。', 'かれはじぶんがてんさいだとこうげんしてはばからない。', 'He declares without hesitation that he is a genius.'),
(100, 87, '事ここに至っては、もはや打つ手がない。', 'ことここにいたっては、もはやうつてがない。', 'Now that things have come to this, there is nothing more to be done.'),
(101, 88, '彼は遅刻を繰り返した挙句、ついには無断欠勤する始末だ。', 'かれはちこくをくりかえしたあげく、ついにはむだんけっきんするしまつだ。', 'After repeated tardiness, he ended up not showing up at all without notice.'),
(102, 89, 'いくら金をためても、死んでしまえばそれまでだ。', 'いくらかねをためても、しんでしまえばそれまでだ。', 'However much money you save, once you die it all comes to nothing.'),
(103, 90, '彼の実力は今さら言うまでもない。', 'かれのじつりょくはいまさらいうまでもない。', 'His ability goes without saying at this point.'),
(104, 91, '厳しく叱るのは、君の将来を思えばこそだ。', 'きびしくしかるのは、きみのしょうらいをおもえばこそだ。', 'I scold you harshly precisely because I care about your future.'),
(105, 92, '売り上げは悪化の一途をたどっている。', 'うりあげはあっかのいっとをたどっている。', 'Sales continue on a steady downward path.');

INSERT INTO vocab (id, word, reading, meaning, part_of_speech) VALUES
(1, '顕著', 'けんちょ', 'remarkable; striking; notable', 'na-adjective'),
(2, '拮抗', 'きっこう', 'rivalry; being evenly matched', 'noun, suru-verb'),
(3, '逸脱', 'いつだつ', 'deviation; departure (from rules or norms)', 'noun, suru-verb'),
(4, '会心', 'かいしん', 'satisfaction; a result one is proud of (会心の出来)', 'noun'),
(5, '顛末', 'てんまつ', 'the whole story; sequence of events from start to finish', 'noun'),
(6, '億劫', 'おっくう', 'bothersome; too much trouble to do', 'na-adjective'),
(7, '怠る', 'おこたる', 'to neglect (a duty); to be remiss in', 'godan verb'),
(8, '賄う', 'まかなう', 'to cover (costs); to provide (meals)', 'godan verb'),
(9, '阻む', 'はばむ', 'to block; to hinder; to impede', 'godan verb'),
(10, '廃れる', 'すたれる', 'to go out of use; to become obsolete; to decline', 'ichidan verb'),
(11, '培う', 'つちかう', 'to cultivate (ability, character); to nurture', 'godan verb'),
(12, '滞る', 'とどこおる', 'to be delayed; to fall into arrears; to stagnate', 'godan verb'),
(13, '捗る', 'はかどる', 'to make good progress; to go smoothly', 'godan verb'),
(14, '憤る', 'いきどおる', 'to be indignant; to resent', 'godan verb'),
(15, '顧みる', 'かえりみる', 'to look back on; to reflect; to give heed to', 'ichidan verb'),
(16, '名残', 'なごり', 'remnants; traces; reluctance to part (名残惜しい)', 'noun'),
(17, '兆し', 'きざし', 'sign; omen; indication (of change)', 'noun'),
(18, '風潮', 'ふうちょう', 'trend of the times; prevailing tendency', 'noun'),
(19, '懸念', 'けねん', 'concern; apprehension; fear', 'noun, suru-verb'),
(20, '妥協', 'だきょう', 'compromise; meeting halfway', 'noun, suru-verb'),
(21, '打開', 'だかい', 'breakthrough; finding a way out (of deadlock)', 'noun, suru-verb'),
(22, '斡旋', 'あっせん', 'mediation; good offices; placement services', 'noun, suru-verb'),
(23, '暫定', 'ざんてい', 'provisional; tentative (暫定的)', 'noun'),
(24, '逼迫', 'ひっぱく', 'being strained; tightness (of finances, supply)', 'noun, suru-verb'),
(25, '円滑', 'えんかつ', 'smooth; harmonious (progress, relations)', 'na-adjective'),
(26, '緻密', 'ちみつ', 'minute; precise; finely detailed (plan, analysis)', 'na-adjective'),
(27, '杜撰', 'ずさん', 'sloppy; careless; slipshod (work, management)', 'na-adjective'),
(28, '露骨', 'ろこつ', 'blatant; undisguised; frank to the point of rudeness', 'na-adjective'),
(29, '頑丈', 'がんじょう', 'sturdy; solid; robust', 'na-adjective'),
(30, '猛烈', 'もうれつ', 'fierce; intense; violent', 'na-adjective'),
(31, '華奢', 'きゃしゃ', 'delicate; slender; fragile-looking', 'na-adjective'),
(32, '質素', 'しっそ', 'simple; frugal; plain (living)', 'na-adjective'),
(33, '頻繁', 'ひんぱん', 'frequent; incessant', 'na-adjective'),
(34, '不備', 'ふび', 'deficiency; inadequacy; defect (in documents, systems)', 'noun'),
(35, '手際', 'てぎわ', 'skill; dexterity; workmanship (手際がいい)', 'noun'),
(36, '見込み', 'みこみ', 'prospect; expectation; promise (見込みがある)', 'noun'),
(37, '目論見', 'もくろみ', 'plan; scheme; intention', 'noun'),
(38, '思惑', 'おもわく', 'expectation; calculation; speculation; others opinions', 'noun'),
(39, '憶測', 'おくそく', 'conjecture; speculation; guesswork', 'noun, suru-verb'),
(40, '折衷', 'せっちゅう', 'blending; compromise between two things (和洋折衷)', 'noun, suru-verb'),
(41, '拍車', 'はくしゃ', 'spur; 拍車をかける: to accelerate, spur on', 'noun'),
(42, '網羅', 'もうら', 'covering exhaustively; comprising everything', 'noun, suru-verb'),
(43, '冒頭', 'ぼうとう', 'opening; beginning (of a speech, document)', 'noun'),
(44, '軌道', 'きどう', 'orbit; track; 軌道に乗る: to get on track', 'noun'),
(45, '克服', 'こくふく', 'conquest (of difficulty, illness); overcoming', 'noun, suru-verb'),
(46, '腐敗', 'ふはい', 'decay; rot; corruption (political, moral)', 'noun, suru-verb'),
(47, '飽和', 'ほうわ', 'saturation (market, capacity)', 'noun, suru-verb'),
(48, '示唆', 'しさ', 'suggestion; implication (示唆に富む)', 'noun, suru-verb'),
(49, '踏襲', 'とうしゅう', 'following (a precedent); carrying on (a policy)', 'noun, suru-verb'),
(50, '謙虚', 'けんきょ', 'modest; humble', 'na-adjective');
